Python有许多 [内置的异常](https://www.programiz.com/python-programming/exceptions) ，当程序中的某些错误出现时，它们会强制您的程序输出错误。

但是，有时您可能需要创建自己的自定义例外来满足您的目的。

---

## 创建自定义例外

在Python中，用户可以通过创建新类来定义自定义异常。 必须从内置 `Exception` 类 直接或间接派生此异常 类。 大多数内置异常也是从此类派生的。

```
>>> class CustomError(Exception):
...     pass
...

>>> raise CustomError
Traceback (most recent call last):
...
__main__.CustomError

>>> raise CustomError("An error occurred")
Traceback (most recent call last):
...
__main__.CustomError: An error occurred
```

在这里，我们创建了一个用户定义的异常 `CustomError` ，该 异常 从 `Exception` 类 继承 。 与其他异常一样，可以使用 `raise` 带有可选错误消息 的 语句 来引发此新异常 。

在开发大型Python程序时，最好将程序引发的所有用户定义的异常放在单独的文件中。 许多标准模块可以做到这一点。 他们分别将例外定义为 `exceptions.py` 或 `errors.py` （通常但并非总是如此）。

用户定义的异常类可以实现普通类可以执行的所有操作，但是我们通常使它们简单明了。 大多数实现都声明一个自定义基类，并从该基类派生其他异常类。 在下面的示例中，将使该概念更清晰。

---

## 示例：Python中的用户定义异常

在此示例中，我们将说明如何在程序中使用用户定义的异常来引发和捕获错误。

该程序将要求用户输入一个数字，直到他们正确猜测一个存储的数字为止。 为了帮助他们解决问题，提供了一个提示，提示他们的猜测是否大于或小于存储的数字。

```py
# define Python user-defined exceptions
class Error(Exception):
    """Base class for other exceptions"""
    pass

class ValueTooSmallError(Error):
    """Raised when the input value is too small"""
    pass

class ValueTooLargeError(Error):
    """Raised when the input value is too large"""
    pass

# you need to guess this number
number = 10

# user guesses a number until he/she gets it right
while True:
    try:
        i_num = int(input("Enter a number: "))
        if i_num < number:
            raise ValueTooSmallError
        elif i_num > number:
            raise ValueTooLargeError
        break
    except ValueTooSmallError:
        print("This value is too small, try again!")
        print()
    except ValueTooLargeError:
        print("This value is too large, try again!")
        print()

print("Congratulations! You guessed it correctly.")
```

这是该程序的示例运行。

Enter a number: 12
This value is too large, try again!

Enter a number: 0
This value is too small, try again!

Enter a number: 8
This value is too small, try again!

Enter a number: 10
Congratulations! You guessed it correctly.

我们定义了一个名为的基类 `Error` 。

我们程序实际引发 的另外两个异常（ `ValueTooSmallError` 和 `ValueTooLargeError` ）是从此类派生的。 这是在Python编程中定义用户定义的异常的标准方法，但您不仅限于这种方法。

---

## 自定义异常类

我们可以进一步自定义此类，以根据需要接受其他参数。

要学习有关自定义Exception类的知识，您需要具有面向对象编程的基础知识。

访问 [Python面向对象编程](https://www.programiz.com/python-programming/object-oriented-programming) ，开始学习 [Python中的面向对象编程](https://www.programiz.com/python-programming/object-oriented-programming) 。

让我们看一个例子：

```py
class SalaryNotInRangeError(Exception):
    """Exception raised for errors in the input salary.

    Attributes:
        salary -- input salary which caused the error
        message -- explanation of the error
    """

    def __init__(self, salary, message="Salary is not in (5000, 15000) range"):
        self.salary = salary
        self.message = message
        super().__init__(self.message)

salary = int(input("Enter salary amount: "))
if not 5000 < salary < 15000:
    raise SalaryNotInRangeError(salary)
```

**输出量**

Enter salary amount: 2000
Traceback (most recent call last):
  File "<string>", line 17, in <module>
    raise SalaryNotInRangeError(salary)
\_\_main\_\_.SalaryNotInRangeError: Salary is not in (5000, 15000) range

在这里，我们重写了 `Exception` 类 的构造函数 以接受我们自己的自定义参数 `salary` 和 `message` 。 然后， 使用参数使用 `Exception` 手动调用 父 类 的构造 `self.message` 函数 `super()` 。

自定义 `self.salary` 属性定义为以后使用。

该类 的继承 `__str__` 方法 `Exception` 然后在 `SalaryNotInRangeError` 引发 时用于显示相应的消息 。

我们还可以 `__str__` 通过覆盖方法来自 定义 方法本身。

```py
class SalaryNotInRangeError(Exception):
    """Exception raised for errors in the input salary.

    Attributes:
        salary -- input salary which caused the error
        message -- explanation of the error
    """

    def __init__(self, salary, message="Salary is not in (5000, 15000) range"):
        self.salary = salary
        self.message = message
        super().__init__(self.message)

    def __str__(self):
        return f'{self.salary} -> {self.message}'

salary = int(input("Enter salary amount: "))
if not 5000 < salary < 15000:
    raise SalaryNotInRangeError(salary)
```

**输出量**

Enter salary amount: 2000
Traceback (most recent call last):
  File "/home/bsoyuj/Desktop/Untitled\-1.py", line 20, in <module>
    raise SalaryNotInRangeError(salary)
\_\_main\_\_.SalaryNotInRangeError: 2000 \-> Salary is not in (5000, 15000) range

---

要了解有关如何在Python中处理异常的更多信息，请访问 [Python异常处理](https://www.programiz.com/python-programming/exception-handling) 。